### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by MinoaBaccus** [DxxxxY/R.A.T#16]
I'm 3 minutes into the tutorial video and I got an error...

https://minoa.has-no-bra.in/5HWR1Gvi_.png

```
PS C:\Users\Minoa\IdeaProjects\R.A.T\server> node .
C:\Users\Minoa\IdeaProjects\R.A.T\server\app.js:71
    .then(async response => {
          ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
PS C:\Users\Minoa\IdeaProjects\R.A.T\server>

```

Please help me -Minoa

**Comment by DxxxxY** [comment]
You changed something, or you're using an outdated version of Nodejs. Can you post your version?

**Comment by MinoaBaccus** [comment]
16.17.0

**Comment by DxxxxY** [comment]
Seems fine, I don't know why this error pops up. The code is identical yet it poses no problems on my end. You are one of the first. Try again I guess.

**Comment by DxxxxY** [comment]
Closed due to inactivity + non-relation to the repo.
